### ISSUE TITLE
🆕 Emoji Bug Report

### ISSUE THREAD

**Issue by behicsakar** [Doist/todoist-python#49] opened 2018-11-18 11:38 UTC
When i try to read one task that is included character '\U0001f195' , i am getting following error

```    print(task)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f195' in position 97: ordinal not in range(128)
```

**Comment by PotHix** [comment] 2019-08-08 10:00
It's fixed in the version 8.0.0, I cannot reproduce it anymore. :+1:

**Closed by PotHix** 2019-08-08 10:00 UTC
